import { showToast, showConfirm } from '../ui/toast.js';
import { escapeHtml, formatMoney, formatDate, formatTime, normalizeText } from '../utils/formatters.js';
let supabase=null,currentCollections=[],merchantsList=[],machinesList=[],listsLoaded=false,isSavingCollection=false;
export function initCollectionsPage(){ supabase=window.supabaseClient; }
async function ensureLists(force=false){ if(listsLoaded&&!force)return; const [m1,m2]=await Promise.all([supabase.from('merchants').select('*'),supabase.from('machines').select('*')]); if(m1.error) throw m1.error; if(m2.error) throw m2.error; merchantsList=m1.data||[]; machinesList=m2.data||[]; listsLoaded=true; }
function merchantLabel(m){ return `${m['رقم التاجر']} - ${m['اسم التاجر']} (${m['اسم النشاط']||'غير محدد'})`; }
function merchantById(id){ return merchantsList.find(m=>m.id===id); }
function resolveMerchant(v){ const raw=String(v||'').trim(),norm=normalizeText(raw); return merchantsList.find(x=>{ const code=String(x['رقم التاجر']||''),name=String(x['اسم التاجر']||''),activity=String(x['اسم النشاط']||''),full=merchantLabel(x); return code===raw||full===raw||normalizeText(code)===norm||normalizeText(name).includes(norm)||normalizeText(activity).includes(norm)||normalizeText(full).includes(norm);})||null; }
function fillMerchantDatalist(){ const dl=document.getElementById('merchantDatalistColl'); if(dl) dl.innerHTML=merchantsList.map(m=>`<option value="${escapeHtml(merchantLabel(m))}"></option>`).join(''); }
function fillMachinesSelect(merchantId='',selected=''){ const el=document.getElementById('collMachineId'); if(!el)return; const filtered=merchantId?machinesList.filter(m=>m['رقم التاجر']===merchantId):[]; el.innerHTML='<option value="">بدون مكنة</option>'+filtered.map(m=>`<option value="${escapeHtml(m['رقم المكنة'])}" ${m['رقم المكنة']===selected?'selected':''}>${escapeHtml(m['رقم المكنة'])}</option>`).join(''); }
function attachSearch(){ const s=document.getElementById('collMerchantSearch'),h=document.getElementById('collMerchantId'); if(!s||!h)return; s.oninput=()=>{ const m=resolveMerchant(s.value); h.value=m?.id||''; if(m) fillMachinesSelect(m.id); }; s.onchange=()=>{ const m=resolveMerchant(s.value); h.value=m?.id||''; s.value=m?merchantLabel(m):''; fillMachinesSelect(m?.id||''); }; }
async function getMerchantDebt(merchantId, excludeCollectionId=null){ const [tRes,cRes]=await Promise.all([supabase.from('transfers').select('*').eq('رقم التاجر',merchantId),supabase.from('collections').select('*').eq('رقم التاجر',merchantId)]); if(tRes.error) throw tRes.error; if(cRes.error) throw cRes.error; const totalT=(tRes.data||[]).reduce((s,r)=>s+(parseFloat(r['قيمة التحويل'])||0),0); const totalC=(cRes.data||[]).filter(r=>!excludeCollectionId||r.id!==excludeCollectionId).reduce((s,r)=>s+(parseFloat(r['قيمة التحصيل'])||0),0); return Math.max(0,totalT-totalC); }
function getNowDateTime(){ const now=new Date(); return {date:now.toISOString().split('T')[0], time:now.toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:true})}; }
function buildDateTime(d,t){ try{return new Date(`${d||''} ${t||'12:00 AM'}`).getTime()||0;}catch{return 0;} }
function clearForm(){ document.getElementById('editCollectionId').value=''; document.getElementById('collMerchantId').value=''; document.getElementById('collMerchantSearch').value=''; document.getElementById('collAmount').value=''; document.getElementById('collType').value='نقدي'; document.getElementById('collNotes').value=''; fillMachinesSelect(''); }
export async function loadCollections(){ supabase=supabase||window.supabaseClient; if(!supabase)return; try{ const {data,error}=await supabase.from('collections').select('*'); if(error) throw error; currentCollections=(data||[]).sort((a,b)=>buildDateTime(b['التاريخ'],b['الوقت'])-buildDateTime(a['التاريخ'],a['الوقت'])); await ensureLists(true); renderCollectionsTable(); }catch(err){ console.error(err); showToast('خطأ في تحميل التحصيلات','error'); } }
function renderCollectionsTable(){ const tbody=document.getElementById('collectionsTableBody'); if(!tbody)return; if(!currentCollections.length){ tbody.innerHTML='<tr><td colspan="10" class="empty-state">لا توجد تحصيلات</td></tr>'; return; } tbody.innerHTML=currentCollections.map((t,idx)=>`<tr><td>${idx+1}</td><td><code class="ref-code">${escapeHtml(t['الرقم المرجعي']||'-')}</code></td><td>${formatDate(t['التاريخ'])}</td><td>${formatTime(t['الوقت'])}</td><td>${escapeHtml(t['اسم التاجر']||'-')}</td><td>${escapeHtml(t['اسم النشاط']||'-')}</td><td>${formatMoney(t['قيمة التحصيل']||0)}</td><td>${formatMoney(t['المتبقي بعد التحصيل']||0)}</td><td>${escapeHtml(t['ملاحظات']||'-')}</td><td><div class="action-btns"><button class="btn btn-primary btn-sm" onclick="window.editCollection('${t.id}')"><i class="fas fa-edit"></i></button><button class="btn btn-danger btn-sm" onclick="window.deleteCollection('${t.id}')"><i class="fas fa-trash"></i></button></div></td></tr>`).join(''); }
export async function openCollectionModal(collection=null){ await ensureLists(true); fillMerchantDatalist(); attachSearch(); if(!collection) clearForm(); document.getElementById('collectionModalTitle').innerHTML=collection?'<i class="fas fa-edit"></i> تعديل تحصيل':'<i class="fas fa-hand-holding-usd"></i> تحصيل جديد'; document.getElementById('editCollectionId').value=collection?.id||''; const merchant=merchantById(collection?.['رقم التاجر']); document.getElementById('collMerchantId').value=merchant?.id||''; document.getElementById('collMerchantSearch').value=merchant?merchantLabel(merchant):''; fillMachinesSelect(merchant?.id||'', collection?.['رقم المكنة']||''); document.getElementById('collAmount').value=collection?.['قيمة التحصيل']||''; document.getElementById('collType').value=collection?.['نوع التحصيل']||'نقدي'; document.getElementById('collNotes').value=collection?.['ملاحظات']||''; document.getElementById('collectionModal').classList.add('show'); }
export function closeCollectionModal(){ document.getElementById('collectionModal')?.classList.remove('show'); clearForm(); }
export async function saveCollection(){ if(isSavingCollection) return; isSavingCollection=true; try{ const id=document.getElementById('editCollectionId').value; const merchant=merchantById(document.getElementById('collMerchantId').value); if(!merchant) return showToast('يرجى اختيار التاجر من القائمة','warning'); const amount=parseFloat(document.getElementById('collAmount').value||'0'); if(!(amount>0)) return showToast('يرجى إدخال مبلغ صحيح','warning'); const currentDebt=await getMerchantDebt(merchant.id,id||null); if(amount>currentDebt) return showToast(`مبلغ التحصيل (${formatMoney(amount)}) أكبر من المديونية الحالية (${formatMoney(currentDebt)})`,'warning'); const {date,time}=getNowDateTime(); const payload={'رقم التاجر':merchant.id,'اسم التاجر':merchant['اسم التاجر'],'اسم النشاط':merchant['اسم النشاط']||'غير محدد','رقم الحساب':merchant['رقم الحساب']||'','رقم المكنة':document.getElementById('collMachineId').value||null,'قيمة التحصيل':amount,'نوع التحصيل':document.getElementById('collType').value||'نقدي','المتبقي بعد التحصيل':Math.max(0,currentDebt-amount),'ملاحظات':document.getElementById('collNotes').value.trim(),'التاريخ':date,'الوقت':time}; const q=id?supabase.from('collections').update(payload).eq('id',id):supabase.from('collections').insert([payload]); const {error}=await q; if(error) throw error; showToast(id?'تم تحديث التحصيل':'تم إضافة التحصيل','success'); closeCollectionModal(); await loadCollections(); window.loadDashboardStats?.(); window.loadRecentActivities?.(); }catch(err){ console.error(err); showToast(err.message||'فشل حفظ التحصيل','error'); } finally{ isSavingCollection=false; } }
export function editCollection(id){ const item=currentCollections.find(t=>t.id===id); if(item) openCollectionModal(item); }
export function deleteCollection(id){ showConfirm('هل تريد حذف هذا التحصيل؟', async()=>{ const {error}=await supabase.from('collections').delete().eq('id',id); if(error) return showToast(error.message,'error'); showToast('تم حذف التحصيل','success'); await loadCollections(); window.loadDashboardStats?.(); window.loadRecentActivities?.(); }); }
window.openCollectionModal=openCollectionModal; window.closeCollectionModal=closeCollectionModal; window.saveCollection=saveCollection; window.editCollection=editCollection; window.deleteCollection=deleteCollection;
